global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'zeam'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zeam_app'
    static_configs:
      - targets: ['localhost:9667']
