[package]
name = "risc0-glue"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "3.0.3" }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.2"

[lib]
crate-type = ["staticlib"]
name = "risc0_glue"