[workspace]
members = [
    "rustglue",
    "risc0",
    "openvm",
    # "powdr",  # Excluded from build - kept as reference only
]
resolver = "2"

[profile.release]
debug = false
lto = true  # Enable full LTO for maximum size reduction
codegen-units = 1  # Single codegen unit for best optimization
opt-level = "s"  # Optimize for size (better than "z" for this project)
strip = false  # Don't strip symbols to avoid conflicts