[package]
name = "rustglue"
version = "0.1.0"
edition = "2021"

[features]
default = ["libp2p"]
risc0 = ["dep:risc0-zkvm"]
openvm = ["dep:openvm-platform", "dep:openvm-sdk", "dep:openvm-build", "dep:openvm-stark-sdk", "dep:openvm-transpiler"]
hashsig = ["dep:hashsig", "dep:rand", "dep:rand_chacha", "dep:thiserror"]
libp2p = ["dep:libp2p", "dep:libp2p-mplex", "dep:futures", "dep:tokio"]

# Convenience feature combinations
networking = ["libp2p"]
zkvms = ["risc0", "openvm", "hashsig"]
crypto = ["hashsig"]
full = ["libp2p", "hashsig", "risc0", "openvm"]

[dependencies]
# Core dependencies (always included)
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.2"
bincode = "1.3"
snap = "1"
sha2 = "0.9"
hex = "0.4.3"

# Optional dependencies controlled by features
risc0-zkvm = { version = "3.0.3", optional = true }
openvm-platform = { package = "openvm", git = "https://github.com/openvm-org/openvm.git", tag = "v1.3.0", features = ["std"], optional = true }
openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.3.0", optional = true }
openvm-build = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.3.0", optional = true }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.1.1", optional = true }
openvm-transpiler = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.3.0", optional = true }
hashsig = { git = "https://github.com/b-wagn/hash-sig", rev = "93eabbf76665b3922da9f05777bd3f5957644e92", optional = true }
rand = { version = "0.9.2", optional = true }
rand_chacha = { version = "0.9.0", optional = true }
thiserror = { version = "2.0.17", optional = true }
libp2p-mplex = { version = "0.42", optional = true }
futures = { version = "0.3.31", optional = true }
tokio = { version = "1", features = ["full"], optional = true }
libp2p = { version = "0.54", default-features = false, features = ["identify", "yamux", "noise", "dns", "tcp", "tokio", "plaintext", "secp256k1", "macros", "ecdsa", "metrics", "quic", "upnp", "ping", "gossipsub"], optional = true }

[lib]
crate-type = ["staticlib"]

[profile.release]
# LTO (Link Time Optimization) is disabled to avoid symbol conflicts between risc0 and openvm.
# Both define the same runtime symbols (like sys_alloc_aligned) which collide when LTO merges
# all code into a single module. Re-enable LTO if building separate binaries for each prover.
lto = false  # Set to true for single-prover builds to reduce binary size from 108MB to ~46MB
strip = "symbols"
codegen-units = 16  # Multiple units keep risc0 and openvm code separate
