[package]
name = "zeam-powdr"
version = "0.1.0"
edition = "2021"

[features]
default = []
simd = ["powdr/plonky3-simd"]

[dependencies]
powdr = { git = "https://github.com/gballet/powdr", branch = "fixes-for-zeam-powdr-prover", features = ["plonky3"] }
serde = { version = "1.0", default-features = false, features = [
  "alloc",
  "derive",
  "rc",
] }
env_logger = "0.10.2"
log = "0.4.17"

[lib]
name = "zeam_powdr"
crate-type = ["staticlib"]
