on:
  push:
    # We intentionally don't run push on feature branches
    branches: [main]
  pull_request:
  workflow_dispatch:

# only one can run at a time in PRs
concurrency:
  # If PR, cancel prev commits. head_ref = source branch name on pull_request, null if push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2.0.5
      with:
        version: 0.14.1

    - name: Cache Zig packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/zig
        key: ${{ runner.os }}-zig-packages-${{ hashFiles('build.zig.zon') }}
        restore-keys: |
          ${{ runner.os }}-zig-packages-

    - name: Set up Rust/Cargo
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Verify installation
      run: |
        rustc --version
        cargo --version

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Check Rust formatting
      run: |
        cargo fmt --manifest-path rust/Cargo.toml --all -- --check

    - name: Run clippy on hosts
      run: |
        cargo clippy --manifest-path rust/Cargo.toml --workspace -- -D warnings

    - name: Lint
      run: zig fmt --check .

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2.0.5
      with:
        version: 0.14.1

    - name: Set up Rust/Cargo
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly

    - name: Install binutils (for objcopy)
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y binutils
        elif [ "${{ runner.os }}" == "macOS" ]; then
          brew install binutils
          echo "$(brew --prefix)/opt/binutils/bin" >> $GITHUB_PATH
        fi

    - name: Cache Zig packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/zig
        key: ${{ runner.os }}-zig-packages-${{ hashFiles('build.zig.zon') }}
        restore-keys: |
          ${{ runner.os }}-zig-packages-

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "rust -> target"
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: build
      run: zig build all

  build-all-provers:
    name: build-all-provers
    runs-on: ${{ matrix.os }}
    needs: build  # Only run if the build job succeeds
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2.0.5
      with:
        version: 0.14.1

    - name: Set up Rust/Cargo
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: clippy, rustfmt

    - name: Install binutils (for objcopy)
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y binutils
        elif [ "${{ runner.os }}" == "macOS" ]; then
          brew install binutils
          echo "$(brew --prefix)/opt/binutils/bin" >> $GITHUB_PATH
        fi

    - name: Cache Zig packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/zig
        key: ${{ runner.os }}-zig-packages-${{ hashFiles('build.zig.zon') }}
        restore-keys: |
          ${{ runner.os }}-zig-packages-

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "rust -> target"
        key: ${{ runner.os }}-cargo-all-provers-${{ hashFiles('**/Cargo.lock') }}

    - name: Build with all provers
      run: zig build -Dprover=all

  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2.0.5
      with:
        version: 0.14.1

    - name: Set up Rust/Cargo
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly

    - name: Install binutils (for objcopy)
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y binutils
        elif [ "${{ runner.os }}" == "macOS" ]; then
          brew install binutils
          echo "$(brew --prefix)/opt/binutils/bin" >> $GITHUB_PATH
        fi

    - name: Cache Zig packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/zig
        key: ${{ runner.os }}-zig-packages-${{ hashFiles('build.zig.zon') }}
        restore-keys: |
          ${{ runner.os }}-zig-packages-

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "rust -> target"
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}

    - name: Run all unit tests
      run: zig build test --summary all

    - name: Run all sim tests
      run: zig build simtest --summary all
    
    - name: Run all spec tests
      run: zig build spectest --summary all  

  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    needs: [lint, build, test, build-all-provers]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to get git commit info

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false  # Don't push, just build to verify
        tags: zeam:ci-${{ github.run_number }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
