on:
  push:
    # We intentionally don't run push on feature branches
    branches: [main]
  pull_request:
  workflow_dispatch:

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.14.0

    - name: Set up Rust/Cargo
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Verify installation
      run: |
        rustc --version
        cargo --version

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run clippy on hosts
      run: |
        cargo clippy --manifest-path rust/Cargo.toml -- -D warnings

    - name: Lint
      run: zig fmt --check *.zig

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.14.0

    - name: build
      run: zig build

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.14.0
    
    - name: Test
      # figure out how to build the monorepo builds
      run: zig build test  --summary all
