on:
  push:
    # We intentionally don't run push on feature branches
    branches: [main]
  pull_request:
  workflow_dispatch:

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.14.0

    - name: Lint
      run: zig fmt --check *.zig

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.14.0

    - name: build
      run: zig build

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: korandoru/setup-zig@v1
      with:
        zig-version: 0.14.0
    
    - name: Test
      # figure out how to build the monorepo builds
      run: zig build test  --summary all
