name: Docker CI

on:
  push:
    branches: [ main, docker-ci ]
  release:
    types: [ published ]
  workflow_dispatch:


env:
  REGISTRY: docker.io
  IMAGE_NAME: blockblaz/zeam

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=always-test-${{ github.run_number }}

    - name: Debug generated tags
      run: |
        echo "🔍 Event: ${{ github.event_name }}"
        echo "🌿 Branch: ${{ github.ref_name }}"
        echo "📋 Generated tags:"
        echo "${{ steps.meta.outputs.tags }}"
        echo ""
        echo "🏷️  Individual tags:"
        echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' | while read tag; do
          [ -n "$tag" ] && echo "  - $tag"
        done
        echo ""
        echo "📊 Tag count: $(echo '${{ steps.meta.outputs.tags }}' | tr ',' '\n' | grep -v '^$' | wc -l)"

    - name: Build and push Docker images
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Image digest
      run: echo "Images pushed with digest ${{ steps.meta.outputs.digest }}"
