on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
  workflow_dispatch:

# only one can run at a time in PRs
concurrency:
  # If PR, cancel prev commits. head_ref = source branch name on pull_request, null if push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: risc0

jobs:
  risc0:
    runs-on: ubuntu-latest
    if: >
      github.event_name != 'pull_request' ||  contains(github.event.pull_request.labels.*.name, 'stf')

    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2.0.5
      with:
        version: 0.14.1

    - name: Cache Zig packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/zig
        key: ${{ runner.os }}-zig-packages-${{ hashFiles('build.zig.zon') }}
        restore-keys: |
          ${{ runner.os }}-zig-packages-

    - name: Set up Rust/Cargo
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: pkgs/state-transition-runtime/src/risc0/host
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}

    - name: Install risc0
      run: |
        curl -L https://risczero.com/install | bash
        /home/runner/.risc0/bin/rzup install r0vm 3.0.3

    - name: run prover
      run: zig build run -- prove -z risc0
