on:
  push:
    branches: [ main ]
  workflow_dispatch:


name: risc0

jobs:
  risc0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Zig
      uses: mlugg/setup-zig@v2.0.5
      with:
        version: 0.14.1

    - name: Set up Rust/Cargo
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: pkgs/state-transition-runtime/src/risc0/host
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}

    - name: Install risc0
      run: |
        curl -L https://risczero.com/install | bash
        /home/runner/.risc0/bin/rzup install r0vm 3.0.0-rc.1

    - name: run prover
      run: zig build run -- prove -z risc0
